-- GENERATED BY competitive-overhaul-v3-20260823
-- Optional Supabase aggregates for Secretkeeper stars and Guesser quests.
-- The client patch remains backward-compatible and can compute these values
-- from rounds JSON before this migration is applied.

begin;

alter table public.matches
  add column if not exists total_stars integer not null default 0,
  add column if not exists total_quests_fulfilled integer not null default 0,
  add column if not exists stars_by_user jsonb not null default '{}'::jsonb,
  add column if not exists quests_by_user jsonb not null default '{}'::jsonb;

alter table public.matches
  drop constraint if exists matches_total_stars_nonnegative,
  add constraint matches_total_stars_nonnegative check (total_stars >= 0),
  drop constraint if exists matches_total_quests_nonnegative,
  add constraint matches_total_quests_nonnegative check (total_quests_fulfilled >= 0);

create or replace function public.refresh_match_competitive_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  round_row jsonb;
  history_row jsonb;
  setter_id text;
  guesser_id text;
  explicit_round_stars integer;
  history_stars integer;
  round_stars integer;
  round_quests integer;
  stars_map jsonb := '{}'::jsonb;
  quests_map jsonb := '{}'::jsonb;
begin
  new.total_stars := 0;
  new.total_quests_fulfilled := 0;

  for round_row in
    select value
    from jsonb_array_elements(coalesce(new.rounds::jsonb, '[]'::jsonb))
  loop
    setter_id := nullif(round_row ->> 'setter', '');
    guesser_id := nullif(round_row ->> 'guesser', '');

    history_stars := 0;
    for history_row in
      select value
      from jsonb_array_elements(coalesce(round_row -> 'history', '[]'::jsonb))
    loop
      history_stars := history_stars + greatest(
        coalesce(nullif(history_row ->> 'starsEarned', '')::integer, 0),
        0
      );
    end loop;

    explicit_round_stars := nullif(round_row ->> 'starsEarned', '')::integer;
    round_stars := greatest(coalesce(explicit_round_stars, history_stars, 0), 0);
    round_quests := greatest(
      coalesce(nullif(round_row ->> 'questsFulfilled', '')::integer, 0),
      0
    );

    new.total_stars := new.total_stars + round_stars;
    new.total_quests_fulfilled := new.total_quests_fulfilled + round_quests;

    if setter_id is not null then
      stars_map := jsonb_set(
        stars_map,
        array[setter_id],
        to_jsonb(coalesce((stars_map ->> setter_id)::integer, 0) + round_stars),
        true
      );
    end if;

    if guesser_id is not null then
      quests_map := jsonb_set(
        quests_map,
        array[guesser_id],
        to_jsonb(coalesce((quests_map ->> guesser_id)::integer, 0) + round_quests),
        true
      );
    end if;
  end loop;

  new.stars_by_user := stars_map;
  new.quests_by_user := quests_map;
  return new;
end;
$$;

drop trigger if exists matches_refresh_competitive_stats on public.matches;
create trigger matches_refresh_competitive_stats
before insert or update of rounds on public.matches
for each row execute function public.refresh_match_competitive_stats();

create index if not exists matches_total_stars_idx
  on public.matches (total_stars desc);
create index if not exists matches_total_quests_fulfilled_idx
  on public.matches (total_quests_fulfilled desc);
create index if not exists matches_stars_by_user_gin_idx
  on public.matches using gin (stars_by_user);
create index if not exists matches_quests_by_user_gin_idx
  on public.matches using gin (quests_by_user);

-- Backfill. For a very large production table, run this UPDATE in batches.
update public.matches set rounds = rounds;

comment on column public.matches.total_stars is
  'Total Secretkeeper stars archived across all rounds in the match.';
comment on column public.matches.total_quests_fulfilled is
  'Total Guesser quests fulfilled across all rounds in the match.';
comment on column public.matches.stars_by_user is
  'Object mapping player user id to Secretkeeper stars earned in this match.';
comment on column public.matches.quests_by_user is
  'Object mapping player user id to Guesser quests fulfilled in this match.';

commit;
